apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-file
  labels:
    name: deployment-file
spec:
  replicas: 1
  selector:
    matchLabels:
      name: poddeployment
  template:
    metadata:
      labels:
        name: poddeployment
    spec:
      containers:
      - name: flaskcode
        image: gcr.io/rb-munish-playground/poddeploy
        ports:
          - containerPort: 5000
